### ISSUE TITLE
Can I use this?

### ISSUE THREAD

**Issue by playground** [poppinlp/file-changed#4]
Can you provide a little more detail on how I can use this?  I have this project that has multiple apps in it and I only want to the build to build only the apps with files modified.  Is this something that will fit the bill?

**Comment by poppinlp** [comment]
I'll update the README for more detail this afternoon(GTM+8) :)

**Comment by playground** [comment]
That's great.  Thank you.

**Comment by poppinlp** [comment]
Hi. Sry for my late reply.
I have published 1.1.0 to support glob and add comments in README example code.

In your case, you may use `addFile` to add the files which you wanna watch.
Then use `check` to make sure which file changed.
Then `update` and `save` the collection info to disk for next time use.
And the next time you could just `check` and save.

This package could not set a watch glob and auto trigger callback. It may be added in next version. For now, you could do what you want by deal with modified result yourself.

**Comment by playground** [comment]
Hey thanks.

But getting errors when try to npm install --save-dev file-changed
npm ERR! fetch failed https://registry.npmjs.org/@concordance/react/-/react-1.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/@ava/babel-preset-transform-test-files/-/babel-preset-transform-test-files-3.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/@ava/babel-preset-stage-4/-/babel-preset-stage-4-1.1.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/@ava/babel-plugin-throws-helper/-/babel-plugin-throws-helper-2.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/@ava/write-file-atomic/-/write-file-atomic-2.2.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/@ava/write-file-atomic/-/write-file-atomic-2.2.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/@ava/babel-plugin-throws-helper/-/babel-plugin-throws-helper-2.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/@concordance/react/-/react-1.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/@ava/babel-preset-stage-4/-/babel-preset-stage-4-1.1.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/@ava/babel-preset-transform-test-files/-/babel-preset-transform-test-files-3.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/@ava/babel-preset-stage-4/-/babel-preset-stage-4-1.1.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/@concordance/react/-/react-1.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/@ava/babel-plugin-throws-helper/-/babel-plugin-throws-helper-2.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/@ava/babel-preset-transform-test-files/-/babel-preset-transform-test-files-3.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/@ava/write-file-atomic/-/write-file-atomic-2.2.0.tgz
npm ERR! Darwin 16.6.0
npm ERR! argv "/Users/ljeff/.nvm/versions/node/v7.7.2/bin/node" "/Users/ljeff/.nvm/versions/node/v7.7.2/bin/npm" "install" "--save-dev" "file-changed"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

**Comment by poppinlp** [comment]
Seems like npm5 add a scope param in shrinkwrap file which not suits npm4.
Thanks. I'll make a test and fix it tonight (GTM+8).

**Comment by poppinlp** [comment]
Hi. Thanks for report.
May i know if you could fetch these resources directly or not? Such as https://registry.npmjs.org/@concordance/react/-/react-1.0.0.tgz
You may copy this link to browser to make a test.

**Comment by playground** [comment]
Hi, yes, I'm able to fetch https://registry.npmjs.org/@concordance/react/-/react-1.0.0.tgz directly.

**Comment by poppinlp** [comment]
OK, i got it.
Seems like this issue is related to the `scope` param in shrinkwrap file which add by npm5.
I'll make a test and fix it tonight.

**Comment by playground** [comment]
Thanks, I will check back tomorrow :-)

**Comment by poppinlp** [comment]
Hi. I could not reproduce this issue last night on node v7.7.2 and npm v4.1.2.
I'm still looking for what is going on there.
But i'll publish version 1.1.1 which is not include that shrinkwrap file tonight. And you could have a try.
Then weekend days coming and i will have enough time to deal with this issue.

**Comment by poppinlp** [comment]
Already published 1.1.1 yesterday. Try to keep that file and fix this. You may have a try.
If it's not work. I'll remove that file.

**Comment by playground** [comment]
Getting 404's
npm ERR! fetch failed https://registry.npmjs.org/@ava/babel-plugin-throws-helper/-/babel-plugin-throws-helper-2.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/@ava/babel-preset-transform-test-files/-/babel-preset-transform-test-files-3.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/@concordance/react/-/react-1.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/@ava/babel-preset-stage-4/-/babel-preset-stage-4-1.1.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/@ava/write-file-atomic/-/write-file-atomic-2.2.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/@ava/babel-plugin-throws-helper/-/babel-plugin-throws-helper-2.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/@ava/babel-preset-transform-test-files/-/babel-preset-transform-test-files-3.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/@ava/babel-preset-stage-4/-/babel-preset-stage-4-1.1.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/@ava/write-file-atomic/-/write-file-atomic-2.2.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/@concordance/react/-/react-1.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
⸨    ░░░░░░░░░░░░░░⸩ ⠦ loadRequestedDeps: WARN retry will retry, error on last attempt: Error: fetch failed with status code 404

**Comment by poppinlp** [comment]
OK. I published 1.1.2 which not include that file just now. You may have a try.

**Comment by playground** [comment]
Great, that works.  Thanks.  I will try using it.  I hope this will give me work I need.  Thanks again.

**Comment by poppinlp** [comment]
Issues are welcome if there's more features you want. :)

**Comment by playground** [comment]
Will do.  Does new fc() support glob such as /**/*.ts for example

const srcPath = path.resolve(__dirname, '../src/app');
const collection = new fc(`${srcPath}/**/*.ts`, `${srcPath}/**/*.scss`, `${srcPath}/**/*.html`);

**Comment by poppinlp** [comment]
Nope. The path for constructor is the collection file save path.
Files could be added to collection by `addFile` method which support glob.
